Universe           = vanilla
Initialdir         = /sphenix/tg/tg01/commissioning/INTT/work/weiche/my_INTT/cosmic/macros
Executable         = run_cosmicstracking.sh
PeriodicHold       = (NumJobStarts >= 1 && JobStatus == 1)
concurrency_limits = CONCURRENCY_LIMIT_DEFAULT:1000
request_memory     = 4GB
Priority           = 20
job_lease_duration = 86400

runnumber          = 39530
run_events         = 10000
Output             = /sphenix/tg/tg01/commissioning/INTT/work/weiche/my_INTT/cosmic/macros/condor_log/condor_cosmic_$(process).out
Error              = /sphenix/tg/tg01/commissioning/INTT/work/weiche/my_INTT/cosmic/macros/condor_log/condor_cosmic_$(process).err
Log                = /tmp/condor_wctang_1_$(process).log

Arguments          = $(runnumber) $(run_events) $(process)
Queue 29